// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/valeriadamante/Desktop/Dottorato/public/CMSSW_11_2_0_pre9/src/Validation/./make_histogram.cpp";

#endif
